---

# This module will create a new user account, add them to the SUDO group, add your public SSH key to their ~/.ssh/authrized_keys file, and disable the root account.
# To encrypt the password run the following:
# python3 -c 'import crypt,getpass;pw=getpass.getpass();print(crypt.crypt(pw) if (pw==getpass.getpass("Confirm: ")) else exit())'
# Copy the output to the 'password' area of this config.

- name: Add new sudo user account to Ubuntu and disable root account
  hosts: all
  gather_facts: no

  tasks:
    - name: Create new user account
      user:
        name: kwallanodes
        state: absent
        remove: yes