---

# This module will create a new user account, add them to the SUDO group, add your public SSH key to their ~/.ssh/authrized_keys file, and disable the root account.
# To encrypt the password run the following:
# python3 -c 'import crypt,getpass;pw=getpass.getpass();print(crypt.crypt(pw) if (pw==getpass.getpass("Confirm: ")) else exit())'
# Copy the output to the 'password' area of this config.

- name: Add new sudo user account to Ubuntu and disable root account
  hosts: otnodes
  gather_facts: no

  tasks:
    - name: Create new user account
      user:
        name: '{{ add_user_username }}'
        groups: sudo
        append: yes
        state: present
        create_home: yes
        shell: /bin/bash
        password: '{{ add_user_encrypted_password }}'

    - name: Add public key to user's .ssh/authorized_keys file
      authorized_key:
        user: '{{ add_user_username }}'
        state: present
        manage_dir: yes
        key: '{{ add_user_ssh_key }}'

    - name: Disable root from being allowed to login
      replace:
        path: /etc/ssh/sshd_config
        regexp: '#?PermitRootLogin .+'
        replace: 'PermitRootLogin no'

    - name: Disable root account
      user:
        name: root
        password: !

    - name: Disable use of passwords
      replace:
        path: /etc/ssh/sshd_config
        regexp: '#?PasswordAuthentication .+'
        replace: 'PasswordAuthentication no'

    - name: Force use of private keys
      replace:
        path: /etc/ssh/sshd_config
        regexp: '#?PubkeyAuthentication .+'
        replace: 'PubkeyAuthentication yes'

    - name: Restart SSH daemon
      service:
        name: sshd
        state: restarted
